### ISSUE TITLE
Android CADT complains that org.chromium.iossocketscommon plugin is missing

### ISSUE THREAD

**Issue by mmocny** [MobileChromeApps/chrome-app-developer-tool#47]
Causes a "1 missing" plugin message to be displayed when CrSpec is loaded, even though that plugin isn't required on Android.

**Comment by agrieve** [comment]
believe this is fixed.

**Comment by smartavionics** [comment]
Hi,
I have just run into this situation using the v0.13.0 release binary running on a Moto G (4.4.4). I have tried building from the latest source but I have a problem with that also, it fails with:

A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find any version that matches com.android.support:support-v4:+.

Any help would be appreciated.
