### ISSUE TITLE
Command: cordova build ios  fails

### ISSUE THREAD

**Issue by ivanixgames** [MobileChromeApps/chrome-app-developer-tool#56]
Hello,
I am trying to build the iOS version of CADT as per the instructions in the README.md
However the coordova build command fails.
I am able to compile a hello world example using cordova sample and also compile other simple chrome apps using caa. 
 
Has anyone run into similar issue ?

The output follows below:

Generating config.xml from defaults for platform "ios"
Calling plugman.prepare for platform "ios"
Preparing ios project
Processing configuration changes for plugins.
Iterating over installed plugins: [ 'org.apache.cordova.UrlRemap',
  'org.apache.appharness.AppHarnessUI',
  'org.apache.cordova.file',
  'org.apache.cordova.file-transfer',
  'org.apache.cordova.device',
  'org.apache.cordova.network-information',
  'org.chromium.sockets.tcp',
  'org.chromium.sockets.tcpserver',
  'org.chromium.system.network',
  'org.chromium.zip',
  'org.chromium.common',
  'org.chromium.iossocketscommon' ]
Writing out cordova_plugins.js...
Wrote out iOS Bundle Identifier to "org.chromium.appdevtool"
Wrote out iOS Bundle Version to "0.12.1-dev"
iOS Product Name has not changed (still "Chrome App Developer Tool")
Running command: /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/hooks/after_prepare/after-hook.js /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool
Wrote platforms/ios/www/cdvah/generated/installedPluginsMetadata.js
Renamed cordova_plugins.js -> platforms/ios/www/cordova_plugins_harness.js
Command finished with error code 0: /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/hooks/after_prepare/after-hook.js /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool
Running command: /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/cordova/build 
Building project  : /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome App Developer Tool.xcodeproj
	Configuration : Debug
	Platform      : emulator
Build settings from command line:
    ARCHS = i386
    CONFIGURATION_BUILD_DIR = /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator
    SDKROOT = iphonesimulator8.2
    SHARED_PRECOMPS_DIR = /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/sharedpch
    VALID_ARCHS = i386

Build settings from configuration file '/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/cordova/build-debug.xcconfig':
    CODE_SIGN_IDENTITY = iPhone Developer
    CODE_SIGN_RESOURCE_RULES_PATH = $(SDKROOT)/ResourceRules.plist

=== BUILD TARGET Chrome App Developer Tool OF PROJECT Chrome App Developer Tool WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Copy\ www\ directory build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Script-304B58A110DAC018002A0835.sh
    cd /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios
    /bin/sh -c \"/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Script-304B58A110DAC018002A0835.sh\"

real	0m7.797s
user	0m0.353s
sys	0m0.870s

ProcessInfoPlistFile build/emulator/Chrome\ App\ Developer\ Tool.app/Info.plist Chrome\ App\ Developer\ Tool/Chrome\ App\ Developer\ Tool-Info.plist
    cd /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Work/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    builtin-infoPlistUtility /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome\ App\ Developer\ Tool/Chrome\ App\ Developer\ Tool-Info.plist -genpkginfo /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator/Chrome\ App\ Developer\ Tool.app/PkgInfo -expandbuildsettings -format binary -platform iphonesimulator -additionalcontentfile /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/MainViewController-PartialInfo.plist -o /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator/Chrome\ App\ Developer\ Tool.app/Info.plist

CompileC build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/AppDelegate.o Chrome\ App\ Developer\ Tool/Classes/AppDelegate.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Work/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=6.0 -iquote /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-generated-files.hmap -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-own-target-headers.hmap -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-all-target-headers.hmap -iquote /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-project-headers.hmap -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator/include -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator/usr/local/lib/include -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/UninstalledProducts/include -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/DerivedSources/i386 -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/DerivedSources -F/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator -include /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/sharedpch/Chrome\ App\ Developer\ Tool-Prefix-hbutyhoinxgwoibegvtzilvkvwvl/Chrome\ App\ Developer\ Tool-Prefix.pch -MMD -MT dependencies -MF /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/AppDelegate.d --serialize-diagnostics /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/AppDelegate.dia -c /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome\ App\ Developer\ Tool/Classes/AppDelegate.m -o /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/AppDelegate.o
In file included from /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome App Developer Tool/Classes/AppDelegate.m:28:
/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome App Developer Tool/Classes/AppDelegate.h:30:9: fatal error: 'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>
        ^
1 error generated.

CompileC build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/MainViewController.o Chrome\ App\ Developer\ Tool/Classes/MainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Work/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -fvisibility=hidden -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=6.0 -iquote /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-generated-files.hmap -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-own-target-headers.hmap -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-all-target-headers.hmap -iquote /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Chrome\ App\ Developer\ Tool-project-headers.hmap -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator/include -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator/usr/local/lib/include -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/UninstalledProducts/include -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/DerivedSources/i386 -I/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/DerivedSources -F/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator -include /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/sharedpch/Chrome\ App\ Developer\ Tool-Prefix-hbutyhoinxgwoibegvtzilvkvwvl/Chrome\ App\ Developer\ Tool-Prefix.pch -MMD -MT dependencies -MF /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/MainViewController.d --serialize-diagnostics /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/MainViewController.dia -c /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome\ App\ Developer\ Tool/Classes/MainViewController.m -o /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/MainViewController.o
In file included from /Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome App Developer Tool/Classes/MainViewController.m:28:
/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/Chrome App Developer Tool/Classes/MainViewController.h:28:9: fatal error: 'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>
        ^
1 error generated.

** BUILD FAILED **

The following build commands failed:
	CompileC build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/AppDelegate.o Chrome\ App\ Developer\ Tool/Classes/AppDelegate.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/Chrome\ App\ Developer\ Tool.build/Debug-iphonesimulator/Chrome\ App\ Developer\ Tool.build/Objects-normal/i386/MainViewController.o Chrome\ App\ Developer\ Tool/Classes/MainViewController.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
Error code 65 for command: xcodebuild with args: -xcconfig,/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/cordova/build-debug.xcconfig,-project,Chrome App Developer Tool.xcodeproj,ARCHS=i386,-target,Chrome App Developer Tool,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Volumes/TestVM/Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/build/sharedpch
Command finished with error code 2: /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/cordova/build 
ERROR building one of the platforms: Error: /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Work/Projects/ChromeApps/chrome-app-developer-tool/ChromeAppDevTool/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by tswast** [comment]
I'm running into a similar issue. I can't get it to build for iOS, even with the latest release version

      $ git checkout tags/chrome-app-developer-tool-0.12.0
      $ ./createproject.sh ChromeAppDevTool 
      $ cd ChromeAppDevTool
      $ cordova build ios
      Running command: /Users/tswast/Documents/src/chrome-app-developer-tool/ChromeAppDevTool/hooks/after_prepare/after-hook.js /Users/tswast/Documents/src/chrome-app-developer-tool/ChromeAppDevTool
      Wrote platforms/ios/www/cdvah/generated/installedPluginsMetadata.js
     .
     .
     .
     /Users/tswast/Documents/src/chrome-app-developer-tool/ChromeAppDevTool/plugins/org.chromium.zip/src/ios/SSZipArchive.m:26:5: error: unknown type name 'zipFile'
        zipFile _zip;
        ^
    .
    .
    .
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    1 warning and 20 errors generated.
    ** BUILD FAILED **

I get the same issue if I try to build from HEAD.

    $ rm -r chrome-app-developer-tool/
    $ git clone https://github.com/MobileChromeApps/chrome-app-developer-tool.git
    $ cd chrome-app-developer-tool 

    $ ./createproject.sh ChromeAppDevTool
    Missing dependency: base64-arraybuffer
    Running: npm install
    npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.10.33","npm":"2.1.11"})
    ...
    npm WARN engine agentkeepalive@1.2.1: wanted: {"node":">= 0.11.12"} (current: {"node":"0.10.33","npm":"2.1.11"})
    ...
    Adding ios project...
    iOS project created with cordova-ios@3.8.0 and has a linked CordovaLib
    + set +x
    Installing plugins.
    ...

    $ cd ChromeAppDevTool
    $ cordova build ios
    ...
    /Users/tswast/Documents/src/chrome-app-developer-tool/ChromeAppDevTool/plugins/org.chromium.zip/src/ios/SSZipArchive.m:26:5: error: unknown type name 'zipFile'
    zipFile _zip;
    ...
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    1 warning and 20 errors generated.
    ** BUILD FAILED **

**Comment by tswast** [comment]
I got rid of some of the warnings by updating Node.js and Cordova to the latest version, but I still see build errors relating to Zip and zipFile.
