### ISSUE TITLE
Apk packager plugin

### ISSUE THREAD

**Issue by bil-ash** [MobileChromeApps/chrome-app-developer-tool#61]
What is the current status of the apkpackager plugin? Is it usable now?If yes, please do provide an example.
Development seems to have abruptly stopped some years back,any specific reason?

**Comment by Haemp** [comment]
Pretty sure this project is dead/dying I wouldn't rely on this project for making any new application today

**Comment by bil-ash** [comment]
Any specific reason behind stopping development of the plugin?
The plugin from which it was forked also stopped development abruptly. Actually I would like to use it, if required I can work on it, but for that I would like to know the reason behind the abrupt halting of the project. Any new restriction imposed by android sdk or some other reason?

**Comment by agrieve** [comment]
The reason is just that Chrome team members that were working on this switched to working on PWAs & better Add-to-home-screen. 

Blog post about Chrome Apps:
https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

Blog post about Add to home screen:
https://developers.google.com/web/updates/2017/02/improved-add-to-home-screen

**Comment by bil-ash** [comment]
So may be I could try working on it, if there isn't any other alternatve. Please do let me know if there is any alternative to this plugin which you know

**Comment by bil-ash** [comment]
Thanks, for your earlier answers

**Comment by Haemp** [comment]
@bil-ash This project is really just a wrapper around Cordova with some chrome specific sugar sprinkled in. If your use case is simply to wrap a web-app in an APK then cordoba will do just fine.

**Comment by bil-ash** [comment]
@Haemp Actually my requirement is generating apk on the device. This is because I want to use cordova-plugin-ace along with an apk generator plugin and make an app which can be used for making other apps. The ace,ui,syntax-highliter,etc are done,the thing which remains is a way for packaging the app.
